wandb_version: 1

epoch:
  desc: null
  value: 200
step_per_epoch:
  desc: null
  value: 5000.0
step_per_collect:
  desc: null
  value: 1
test_num:
  desc: null
  value: 10
update_per_step:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 256
wandb_project:
  desc: null
  value: SSAC
resume_id:
  desc: null
  value: 1
logger:
  desc: null
  value: wandb
algo_name:
  desc: null
  value: sac
task:
  desc: null
  value: stabilize
seed:
  desc: null
  value: 3
logdir:
  desc: null
  value: ''
spiking:
  desc: null
  value: false
recurrent:
  desc: null
  value: false
masked:
  desc: null
  value: false
drone:
  desc: null
  value: stock drone
buffer_size:
  desc: null
  value: 300000
collector_type:
  desc: null
  value: Collector
reinit:
  desc: null
  value: true
reward_function:
  desc: null
  value: same as vague voice or snowy spaceship
exploration_noise:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727965320
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.11.9
      5: 0.17.3
      8:
      - 5
      9:
        2: tianshou
      13: linux-x86_64
